packages:
  - packages/*

overrides:
  esbuild@<=0.24.2: 0.25.12
  ws@>=8.0.0 <8.20.1: 8.20.1

allowBuilds:
  '@parcel/watcher': true
  '@reown/appkit': false
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true

# 5/21になったら消す
minimumReleaseAge: 0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
